// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:597da0bd-0362-4e5f-aca7-7a26afad9b8b",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_VkcRxzaBZ",
    "aws_user_pools_web_client_id": "v0e01fp7hfbdlnevm3v5154jp",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://r4egj5s65fabxe3krq2wqpzwhu.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-7sjs4g22qvhfzjhyukajpw2hae"
};


export default awsmobile;
